services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:${PROJECT_FOLDER}
      - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "80:80"
    container_name: project_nginx
    depends_on:
      - app

  app:
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:${PROJECT_FOLDER}
    ports:
      - "5173:5173"
    depends_on:
      - db
    container_name: project_app

  db:
    image: mysql
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_LOWER_CASE_TABLE_NAMES: 1
    ports:
      - "8101:3306"
    container_name: project_db

volumes:
  db_data:
